repos:
-   repo: local
    hooks:
    -   id: check-compilation
        name: check-compilation
        entry: ./scripts/check-compilation.sh
        language: script
        types: [text]
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.7
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: ["-i", "-style=file", "--fallback-style=none"]
